vich_uploader:
    db_driver: orm

    mappings:
       gift:
           uri_prefix: /uploads/gifts
           upload_destination: '%kernel.project_dir%/public/uploads/gifts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       reindeer:
           uri_prefix: /uploads/reindeers
           upload_destination: '%kernel.project_dir%/public/uploads/reindeers'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
